classdef SimulasiKanal < handle
    properties
        jlhbit;
        fdoppler;
        lajubit;
        SNR;
        BER;
    
        Meanf;
        Varf;
        Meann;
        Varn;
        Meanr;
        Varr;
        
        Ts;
        Tc;
        Pe;
        dataHasil;
        keputusanUjiDistribusi;
    end
    
    properties( Access = private )
        win2;
        label19;
        label20;
        label21;
        label22;
        label23;
        label24;
        grafik2;
        grafik3; 
        grafik4;
        grafik5;
        grafik6;
        edit6;
    end
    
    methods        
        function simKanal = createSimulationFigure(simKanal)
            position = [(0.5-(0.65/2)) (0.5-(0.67/2)) 0.65 0.67];
            simKanal.win2=figure(...
                                'units','normalized', ...
                                'position',position, ...
                                'color',[.973 .973 .973], ...
                                'menubar','none', ...
                                'resize','off', ...
                                'numbertitle','off', ...
                                'name','Tampilan Proses Simulasi', ...
                                'WindowStyle', 'modal');
            
            simKanal.label19=uicontrol('parent',simKanal.win2,...
                                        'units','points',...    
                                        'position',[60 380 100 10],...
                                        'backgroundcolor',[.8 .8 .9],...    
                                        'style','Text',...
                                        'string','Data yang Dikirim',...
                                        'fontname','arial',...    
                                        'fontsize',10,...
                                        'foregroundcolor',[0 0 0]);
            simKanal.label20=uicontrol('parent',simKanal.win2,...
                                        'units','points',...    
                                        'position',[260 380 60 10],...
                                        'backgroundcolor',[.8 .8 .9],...    
                                        'style','Text',...
                                        'string','Kanal Fading',...
                                        'fontname','arial',...    
                                        'fontsize',10,...
                                        'foregroundcolor',[0 0 0]);
            simKanal.label21=uicontrol('parent',simKanal.win2,...
                                        'units','points',...    
                                        'position',[470 345 40 10],...
                                        'backgroundcolor',[.8 .8 .9],...    
                                        'style','Text',...
                                        'string','Noise',...
                                        'fontname','arial',...    
                                        'fontsize',10,...
                                        'foregroundcolor',[0 0 0]);
            simKanal.label22=uicontrol('parent',simKanal.win2,...
                                        'units','points',...    
                                        'position',[240 185 100 10],...
                                        'backgroundcolor',[.8 .8 .9],...    
                                        'style','Text',...
                                        'string','Data yang diterima',...
                                        'fontname','arial',...    
                                        'fontsize',10,...
                                        'foregroundcolor',[0 0 0]);
            simKanal.label23=uicontrol('parent',simKanal.win2,...
                                        'units','points',...    
                                        'position',[40 185 140 10],...
                                        'backgroundcolor',[.8 .8 .9],...    
                                        'style','Text',...
                                        'string','Data terima sesudah threshold',...
                                        'fontname','arial',...    
                                        'fontsize',10,...
                                        'foregroundcolor',[0 0 0]);
            simKanal.label24=uicontrol('parent',simKanal.win2,...
                                        'units','points',...    
                                        'position',[475 100 50 10],...
                                        'backgroundcolor',[.8 .8 .9],...    
                                        'style','Text',...
                                        'string','Bit Error',...
                                        'fontname','arial',...    
                                        'fontsize',10,...
                                        'foregroundcolor',[0 0 0]);
            simKanal.grafik2=axes('parent',simKanal.win2,...
                                    'units','pixel',...    
                                    'position',[50 300 200 200],...
                                    'xcolor',[.1 .0 .4],...
                                    'ycolor',[.1 .0 .4],...    
                                    'fontsize',8,...    
                                    'color',[1 1 1]);
            simKanal.grafik3=axes('parent',simKanal.win2,...
                                    'units','pixel',...    
                                    'position',[300 300 200 200],...
                                    'xcolor',[.1 .0 .4],...
                                    'ycolor',[.1 .0 .4],...    
                                    'fontsize',8,...    
                                    'color',[1 1 1]);
            simKanal.grafik4=axes('parent',simKanal.win2,...
                                    'units','pixel',...    
                                    'position',[560 250 200 200],...
                                    'xcolor',[.1 .0 .4],...
                                    'ycolor',[.1 .0 .4],...    
                                    'fontsize',8,...    
                                    'color',[1 1 1]);
            simKanal.grafik5=axes('parent',simKanal.win2,...
                                    'units','pixel',...    
                                    'position',[300 40 200 200],...
                                    'xcolor',[.1 .0 .4],...
                                    'ycolor',[.1 .0 .4],...    
                                    'fontsize',8,...    
                                    'color',[1 1 1]);
            simKanal.grafik6=axes('parent',simKanal.win2,...
                                    'units','pixel',...    
                                    'position',[50 40 200 200],...
                                    'xcolor',[.1 .0 .4],...
                                    'ycolor',[.1 .0 .4],...    
                                    'fontsize',8,...    
                                    'color',[1 1 1]);
            simKanal.edit6=uicontrol('parent',simKanal.win2,...
                                        'units','pixel',...    
                                        'position',[640 100 50 15],...
                                        'backgroundcolor',[1 1 1],...        
                                        'style','Edit',...
                                        'string','',...
                                        'fontname','arial',...    
                                        'fontsize',10);
        end
        
        function simKanal = startSimulation(simKanal, jumlahBit, frekuensiDoppler, lajuBit, pauseInterval)
            createSimulationFigure(simKanal);
            simKanal.jlhbit=jumlahBit;
            simKanal.fdoppler=frekuensiDoppler;
            simKanal.lajubit=lajuBit;
            simKanal.SNR = 0:5:25;
            t1=1:simKanal.jlhbit;
            ts=1/simKanal.lajubit;
            tc=9/(16*pi*simKanal.fdoppler);
            simKanal.Ts = ts;
            simKanal.Tc = tc;
%             set(edit4,'string',Ts);
%             set(edit5,'string',Tc);  
            simKanal.BER   = zeros(1, length(simKanal.SNR));
            simKanal.Meanf = zeros(1, length(simKanal.SNR));
            simKanal.Varf  = zeros(1, length(simKanal.SNR));
            simKanal.Meann = zeros(1, length(simKanal.SNR));
            simKanal.Varn  = zeros(1, length(simKanal.SNR));
            simKanal.Meanr = zeros(1, length(simKanal.SNR));
            simKanal.Varr  = zeros(1, length(simKanal.SNR));
            Mf  = zeros(1, length(simKanal.SNR));
            Vf  = zeros(1, length(simKanal.SNR));
            Mn  = zeros(1, length(simKanal.SNR));
            Vn  = zeros(1, length(simKanal.SNR));
            Mr  = zeros(1, length(simKanal.SNR));
            Vr  = zeros(1, length(simKanal.SNR));
            err = zeros(1, length(simKanal.SNR));

            for i = 1:length(simKanal.SNR)
                for j = 1:10 %Pengulangan untuk 10 kali
                    %Menbangkitkan sinyal acak    
                    signal = (round(resource_simulasiKanal_randmcg(1, simKanal.jlhbit))-0.5)*2;
                    plot(simKanal.grafik2,t1,signal) 
                    set(get(simKanal.grafik2,'XLabel'),'String','time')
                    set(get(simKanal.grafik2,'YLabel'),'String','signal amplitude')
                    %Respons dari kanal fading 
                    f = resource_simulasiKanal_fading(simKanal.jlhbit, simKanal.fdoppler, 1/simKanal.lajubit); 
                    f = abs(f');
                    Mf(i) = mean(f);
                    Vf(i) = var(f);
                    semilogy(simKanal.grafik3,t1,f)
                    set(get(simKanal.grafik3,'XLabel'),'String','time')
                    set(get(simKanal.grafik3,'YLabel'),'String','fading')
                    %Membangkitkan noise AWGN
                    sigma=sqrt(1/10^(simKanal.SNR(i)/10));
                    noise = resource_simulasiKanal_boxmuller(simKanal.jlhbit)*sigma;
                    Mn(i)= mean(noise);
                    Vn(i) = var(noise);
                    plot(simKanal.grafik4,t1,noise)
                    set(get(simKanal.grafik4,'XLabel'),'String','time')
                    set(get(simKanal.grafik4,'YLabel'),'String','noise amplitude')
                    %Hasil yang diterima receiver 
                    r=signal.*f+noise;
                    Mr(i)= mean(r);
                    Vr(i)= var(r);
                    plot(simKanal.grafik5,t1,r)
                    set(get(simKanal.grafik5,'XLabel'),'String','time')
                    set(get(simKanal.grafik5,'YLabel'),'String','signal amplitude')
                    %Data terima sesudah threshold
                    r = sign(r);
                    plot(simKanal.grafik6,t1,r)
                    set(get(simKanal.grafik6,'XLabel'),'String','time')
                    set(get(simKanal.grafik6,'YLabel'),'String','signal amplitude')
                    simKanal.Meanf(i)=simKanal.Meanf(i)+Mf(i);
                    simKanal.Varf(i)=simKanal.Varf(i)+Vf(i);
                    simKanal.Meann(i)=simKanal.Meann(i)+Mn(i);
                    simKanal.Varn(i)=simKanal.Varn(i)+Vn(i);
                    simKanal.Meanr(i)=simKanal.Meanr(i)+Mr(i);
                    simKanal.Varr(i)=simKanal.Varr(i)+Vr(i);
                    %Menghitung jumlah bit yang salah 
                    err(i) = sum(abs(signal-r)/2);
                    set(simKanal.edit6,'string',err(i));
                    simKanal.BER(i) = simKanal.BER(i) + err(i); 
                    pause(0)
                end
                simKanal.Meanf(i)=simKanal.Meanf(i)/10;
                simKanal.Varf(i)=simKanal.Varf(i)/10;
                simKanal.Meann(i)=simKanal.Meann(i)/10;
                simKanal.Varn(i)=simKanal.Varn(i)/10;
                simKanal.Meanr(i)=simKanal.Meanr(i)/10;
                simKanal.Varr(i)=simKanal.Varr(i)/10;
                %Menghitung BER total untuk tiap SNR yang berbeda
                simKanal.BER(i) = simKanal.BER(i)/(10*simKanal.jlhbit);
            end
            %Menghitung nilai BER secara teori
            t = 0:0.5:25;
            simKanal.Pe = 0.5.*(1-sqrt(10.^(t./10)./(1+10.^(t./10))));
            simKanal.dataHasil = [simKanal.SNR' simKanal.BER' simKanal.Meanf' simKanal.Varf' ...
                                  simKanal.Meann' simKanal.Varn' simKanal.Meanr' simKanal.Varr']; 
            close
        end
        
        function simKanal = ujiDistribusiUniform(simKanal) % Status: OK
            if(~isempty(simKanal.jlhbit))
                win3=figure(...
                'units','pixel',...
                    'position',[100 60 600 500],...
                    'color',[.8 .8 .8],...
                    'menubar','none',...
                    'resize','on',...
                    'numbertitle','off',...
                    'name','Uji Distribusi Uniform');
                listbox6=uitable('parent',win3,...
                    'units','pixel',...    
                    'position',[170 100 276.5 320],...
                    'fontname','arial',...    
                    'fontsize',10);
                label25=uicontrol('parent',win3,...
                    'units','pixel',...    
                    'position',[150 450 300 20],...
                    'backgroundcolor',[.8 .8 .8],...    
                    'style','Text',...
                    'string','Uji Distribusi Uniform',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'fontweight','bold',...
                    'foregroundcolor',[.45 .45 .9]);
                label26=uicontrol('parent',win3,...
                    'units','pixel',...    
                    'position',[300 75 50 15],...
                    'backgroundcolor',[.85 .6 .8],...        
                    'style','Text',...
                    'string','',...
                    'fontname','arial',...    
                    'fontsize',10);
                label27=uicontrol('parent',win3,...
                    'units','pixel',...    
                    'position',[200 425 20 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','Qi',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.6 .3 .4]);
                label28=uicontrol('parent',win3,...
                    'units','pixel',...    
                    'position',[260 425 20 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','Ei',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.6 .3 .4]);
                label29=uicontrol('parent',win3,...
                    'units','pixel',...    
                    'position',[320 425 70 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','(Qi-Ei)^2/Ei',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.6 .3 .4]);
                label30=uicontrol('parent',win3,...
                    'units','pixel',...    
                    'position',[200 75 80 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','Statistik Uji',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.65 .6 .4]);
                label31=uicontrol('parent',win3,...
                    'units','pixel',...    
                    'position',[200 50 80 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','Keputusan',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.0 .6 .4]);
                edit7=uicontrol('parent',win3,...
                    'units','pixel',...    
                    'position',[300 50 60 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Edit',...
                    'string','',...
                    'fontname','arial',...    
                    'fontsize',10);
    %             jlhbit=str2num(get(edit1,'string'));
                signal = resource_simulasiKanal_randmcg(1, simKanal.jlhbit);
                k=20;
                Qi=hist(signal,k);
                Ei_awal=simKanal.jlhbit/k;
                Ei = zeros(1, k);
                for j=1:k
                    Ei(j)=Ei_awal;
                end
                X0_kuadrat=(Qi-Ei).^2./Ei;
                tab1=[Qi' Ei' X0_kuadrat'];
                set(listbox6,'data',tab1);
                X0_kuadrat=sum(X0_kuadrat);
                c=0;
                df=k-1-c;
                X1_kuadrat=30.144;
                set(label26,'string',num2str(X0_kuadrat))
                if X0_kuadrat <= X1_kuadrat
                    set(edit7,'string','Diterima','foregroundcolor',[.5 .4 .8]);
                else
                    set(edit7,'string','Ditolak','foregroundcolor',[.8 .4 .1]);
                end
            else
                display('Start a simulation before using this');
            end
        end 
        
        function simKanal = ujiDistribusiRayleight(simKanal)
            if(~isempty(simKanal.jlhbit))
                win5=figure(...
                'units','pixel',...
                    'position',[100 60 600 500],...
                    'color',[.8 .8 .8],...
                    'menubar','none',...
                    'resize','on',...
                    'numbertitle','off',...
                    'name','Uji Distribusi Rayleigh');
                listbox8=uitable('parent',win5,...
                    'units','pixel',...    
                    'position',[200 100 180 320],...
                    'fontname','arial',...    
                    'fontsize',10);
                label40=uicontrol('parent',win5,...
                    'units','pixel',...    
                    'position',[150 450 300 20],...
                    'backgroundcolor',[.8 .8 .8],...    
                    'style','Text',...
                    'string','Uji Distribusi Rayleigh',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'fontweight','bold',...
                    'foregroundcolor',[.4 .4 .4  ]);
                label41=uicontrol('parent',win5,...
                    'units','pixel',...    
                    'position',[300 75 50 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','',...
                    'fontname','arial',...    
                    'fontsize',10);
                label42=uicontrol('parent',win5,...
                    'units','pixel',...    
                    'position',[200 425 20 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','Qi',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.6 .3 .4]);
                label43=uicontrol('parent',win5,...
                    'units','pixel',...    
                    'position',[260 425 20 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','Ei',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.6 .3 .4]);
                label44=uicontrol('parent',win5,...
                    'units','pixel',...    
                    'position',[320 425 70 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','(Qi-Ei)^2/Ei',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.6 .3 .4]);
                label45=uicontrol('parent',win5,...
                    'units','pixel',...    
                    'position',[200 75 80 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','Statistik Uji',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.65 .6 .4]);
                label46=uicontrol('parent',win5,...
                    'units','pixel',...    
                    'position',[200 50 80 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','Keputusan',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.0 .6 .4]);
                edit9=uicontrol('parent',win5,...
                    'units','pixel',...    
                    'position',[300 50 60 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Edit',...
                    'string','',...
                    'fontname','arial',...    
                    'fontsize',10);
                SNR=0;
                f = resource_simulasiKanal_fading(simKanal.jlhbit, simKanal.fdoppler, 1/simKanal.lajubit); 
                f = abs(f');
                k=20;
                [Qi,xout]=hist(f,k);
                selang = xout(1)-min(f);
                batas_bawah=xout-selang;
                batas_atas=xout+selang;
                sigma=raylfit(f);
                p_batas_atas=raylcdf(batas_atas,sigma);
                p_batas_bawah=raylcdf(batas_bawah,sigma);
                Prob=p_batas_atas-p_batas_bawah;
                Ei=simKanal.jlhbit*Prob;
                X0_kuadrat=(Qi-Ei).^2./Ei;
                tab3=[Qi' Ei' X0_kuadrat'];
                set(listbox8,'data',tab3);
                X0_kuadrat=sum(X0_kuadrat);
                c=1;
                df=k-1-c;
                X1_kuadrat=28.869;
                set(label41,'string',num2str(X0_kuadrat,'%2.2f'))
                if X0_kuadrat <= X1_kuadrat
                    set(edit9,'string','Diterima','foregroundcolor',[.5 .4 .8]);
                else
                    set(edit9,'string','Ditolak','foregroundcolor',[.8 .4 .1]);
                end
            else
                display('Start a simulation before using this');
            end
        end
        
        function simKanal = ujiDistribusiNormal(simKanal, pilihandB)
            if(~isempty(simKanal.jlhbit))
                win4=figure(...
                'units','pixel',...
                    'position',[100 60 600 500],...
                    'color',[.8 .8 .8],...
                    'menubar','none',...
                    'resize','on',...
                    'numbertitle','off',...
                    'name','Uji Distribusi Normal');
                listbox7=uitable('parent',win4,...
                    'units','pixel',...    
                    'position',[200 100 180 320],...
                    'fontname','arial',...    
                    'fontsize',10);
                label32=uicontrol('parent',win4,...
                    'units','pixel',...    
                    'position',[150 450 300 20],...
                    'backgroundcolor',[.8 .8 .8],...    
                    'style','Text',...
                    'string','Uji Distribusi Normal',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'fontweight','bold',...
                    'foregroundcolor',[.4 .4 .4  ]);
                label34=uicontrol('parent',win4,...
                    'units','pixel',...    
                    'position',[300 75 50 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','',...
                    'fontname','arial',...    
                    'fontsize',10);
                label35=uicontrol('parent',win4,...
                    'units','pixel',...    
                    'position',[200 425 20 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','Qi',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.6 .3 .4]);
                label36=uicontrol('parent',win4,...
                    'units','pixel',...    
                    'position',[260 425 20 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','Ei',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.6 .3 .4]);
                label37=uicontrol('parent',win4,...
                    'units','pixel',...    
                    'position',[320 425 70 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','(Qi-Ei)^2/Ei',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.6 .3 .4]);
                label38=uicontrol('parent',win4,...
                    'units','pixel',...    
                    'position',[200 75 80 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','Statistik Uji',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.65 .6 .4]);
                label39=uicontrol('parent',win4,...
                    'units','pixel',...    
                    'position',[200 50 80 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Text',...
                    'string','Keputusan',...
                    'fontname','arial',...    
                    'fontsize',10,...
                    'foregroundcolor',[.0 .6 .4]);
                edit8=uicontrol('parent',win4,...
                    'units','pixel',...    
                    'position',[300 50 60 15],...
                    'backgroundcolor',[.8 .8 .8],...        
                    'style','Edit',...
                    'string','',...
                    'fontname','arial',...    
                    'fontsize',10);
                k=20;
                pilihan3 = pilihandB;
                switch pilihan3
                case 1  
                sigma=sqrt(1/10^(0/10));
                noise = resource_simulasiKanal_boxmuller(simKanal.jlhbit)*sigma;
                [Qi,xout]=hist(noise,k);
                case 2  
                sigma=sqrt(1/10^(5/10));
                noise = resource_simulasiKanal_boxmuller(simKanal.jlhbit)*sigma;
                [Qi,xout]=hist(noise,k);
                case 3  
                sigma=sqrt(1/10^(10/10));
                noise = resource_simulasiKanal_boxmuller(simKanal.jlhbit)*sigma;
                [Qi,xout]=hist(noise,k);
                case 4  
                sigma=sqrt(1/10^(15/10));
                noise = resource_simulasiKanal_boxmuller(simKanal.jlhbit)*sigma;
                [Qi,xout]=hist(noise,k);
                case 5  
                sigma=sqrt(1/10^(20/10));
                noise = resource_simulasiKanal_boxmuller(simKanal.jlhbit)*sigma;
                [Qi,xout]=hist(noise,k);
                case 6
                sigma=sqrt(1/10^(25/10));
                noise = resource_simulasiKanal_boxmuller(simKanal.jlhbit)*sigma;
                [Qi,xout]=hist(noise,k);
                end;
                selang = xout(1)-min(noise);
                batas_bawah=xout-selang;
                batas_atas=xout+selang;
                z_batas_atas=batas_atas/sigma;
                z_batas_bawah=batas_bawah/sigma;
                p_batas_atas=normcdf(z_batas_atas);
                p_batas_bawah=normcdf(z_batas_bawah);
                Prob=p_batas_atas-p_batas_bawah;
                Ei=simKanal.jlhbit*Prob;
                X0_kuadrat=(Qi-Ei).^2./Ei;
                tab2=[Qi' Ei' X0_kuadrat'];
                set(listbox7,'data',tab2);
                X0_kuadrat=sum(X0_kuadrat);
                c=2;
                df=k-1-c;
                X1_kuadrat=27.587;
                set(label34,'string',num2str(X0_kuadrat,'%2.2f'))
                if X0_kuadrat <= X1_kuadrat
                    set(edit8,'string','Diterima','foregroundcolor',[.5 .4 .8]);
                else
                    set(edit8,'string','Ditolak','foregroundcolor',[.8 .4 .1]);
                end
            else
                display('Start a simulation before using this');
            end
        end
        
        function simKanal = saveHasilSimulasi(simKanal, fileName)
            if(~isempty(simKanal.jlhbit))
                mkdir 'Saved Results';
                nama_file = ['Saved Results/' fileName '.txt'];
                foutput=fopen(nama_file,'w');
                fprintf(foutput,'========================================================\n');         
                fprintf(foutput,'%52s\n','Tabel Perbandingan BER Hasil Simulasi dengan Hasil Teori');        
                fprintf(foutput,'========================================================\n');   
                fprintf(foutput,'%8s %20s %18s\n','SNR','|    Hasil Simulasi','  |     Hasil Teori');
                fprintf(foutput,'--------------------------------------------------------\n');
                BERt=[simKanal.Pe(1) simKanal.Pe(11) simKanal.Pe(21) simKanal.Pe(31) simKanal.Pe(41) simKanal.Pe(51)];
                for i = 1:6
                    fprintf(foutput,'%7.0f   |%14.5f       |%14.5f\n',simKanal.SNR(i),simKanal.BER(i),BERt(i));
                end
                fprintf(foutput,'--------------------------------------------------------');
                fclose(foutput);
            else
                display('Start a simulation before using this');
            end
        end
    end
end